### ISSUE TITLE
Sub folder routing

### ISSUE THREAD

**Issue by paulcanning** [edwardmp/CodeIgniter-AppEngine#8]
I am having issues getting sub-folder routing to work on App Engine.

I have an "admin" folder inside the controller folder, with an index.php file. On LAMP/WAMP, I could access this (without extra routing) by simply accessing "http://localhost/admin".

On App Engine, this gives me a blank page with a 500 server response.

I have tried adding the following routes, but they still don't work:

$route['admin'] = 'admin/index';
$route['admin/(:any)'] = 'admin/$1';

(I have also tried switching the order)

**Comment by edwardmp** [comment]
Please supply a link to a repository with your code so I can reproduce the issue.

**Comment by nfreear** [comment]
Hi @paulcanning & @edwarmp,

Just a thought, but in `app.yaml` I think you'll need something like

```yaml
# ...

handlers:
  # ...

  - url: /assets/images/*
    static_dir: CodeIgniter_2.1.4/assets/images

  - url: /admin/*
    # Admin front controller.
    script: CodeIgniter_2.1.4/application/controllers/index.php

  - url: /
    # Public front controller.
    script: CodeIgniter_2.1.4/index.php

  - url: /(.+)
    script: CodeIgniter_2.1.4/index.php

# ...
```

Google App Engine doesn't understand `.htaccess` -- its not built on Apache. See,

* https://cloud.google.com/appengine/docs/php/config/appconfig

I hope that helps,


Nick
